using QuanticsGrids: DiscretizedGrid, InherentDiscreteGrid
using QuanticsGrids: quantics_to_grididx, quantics_to_origcoord
using QuanticsGrids: grididx_to_quantics, grididx_to_origcoord
using QuanticsGrids: origcoord_to_quantics, origcoord_to_grididx
